title: Nucleus
description: The Ultimate IDE for Bioinformaticians!
theme: just-the-docs

aux_links:
  "Github":
    - "https://github.com/pratikkatte/Nucleus"
  "Blogs":
    - "docs/blogs"


permalink: pretty

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

search_enabled: true

heading_anchors: true

aux_links_new_tab: true

nav_enabled: true


exclude:
  - docs/blogs